export const data = [
  {
    id: 1,
    description: "Um carro muito maneiro que corre muito rapido",
    year: 1999,
    km: 2344,
    price: 20.434,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/04-images/novo-onix-branco-summit.png?imwidth=419",
    model: "ONIX 01",
    mark: "Chevrolet",
    owner: "Paulo Vitor",
  },
  {
    id: 2,
    description: "Um carro muito maneiro que faz muito barulho pras mina",
    year: 2012,
    km: 4542,
    price: 28.325,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/segmento-carros/01-images/onix-plus-premier.jpg?imwidth=419",
    model: "ONIX PLUS 02",
    mark: "Chevrolet",
    owner: "Ronaldinho das Mina",
  },
  {
    id: 3,
    description: "Muito bão viu, em ótimas condições, nunca deixou na mão.",
    year: 2022,
    km: 1242,
    price: 32.122,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=419",
    model: "CRUZE SPORT6 RS 03",
    mark: "Chevrolet",
    owner: "Reginaldo Rossi",
  },
  {
    id: 4,
    description: "Um carro muito maneiro que corre muito rapido",
    year: 1999,
    km: 2344,
    price: 20.434,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/04-images/novo-onix-branco-summit.png?imwidth=419",
    model: "ONIX 04",
    mark: "Chevrolet",
    owner: "Paulo Vitor",
  },
  {
    id: 5,
    description: "Um carro muito maneiro que faz muito barulho pras mina",
    year: 2012,
    km: 4542,
    price: 28.325,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/segmento-carros/01-images/onix-plus-premier.jpg?imwidth=419",
    model: "ONIX PLUS 05",
    mark: "Chevrolet",
    owner: "Ronaldinho das Mina",
  },
  {
    id: 6,
    description: "Muito bão viu, em ótimas condições, nunca deixou na mão.",
    year: 2022,
    km: 1242,
    price: 32.122,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=419",
    model: "CRUZE SPORT6 RS 06",
    mark: "Chevrolet",
    owner: "Reginaldo Rossi",
  },
  {
    id: 7,
    description: "Um carro muito maneiro que faz muito barulho pras mina",
    year: 2012,
    km: 4542,
    price: 28.325,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/segmento-carros/01-images/onix-plus-premier.jpg?imwidth=419",
    model: "ONIX PLUS 07",
    mark: "Chevrolet",
    owner: "Ronaldinho das Mina",
  },
  {
    id: 8,
    description: "Muito bão viu, em ótimas condições, nunca deixou na mão.",
    year: 2022,
    km: 1242,
    price: 32.122,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=419",
    model: "CRUZE SPORT6 RS 08",
    mark: "Chevrolet",
    owner: "Reginaldo Rossi",
  },
  {
    id: 9,
    description: "Um carro muito maneiro que corre muito rapido",
    year: 1999,
    km: 2344,
    price: 20.434,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/04-images/novo-onix-branco-summit.png?imwidth=419",
    model: "ONIX 09",
    mark: "Chevrolet",
    owner: "Paulo Vitor",
  },
  {
    id: 10,
    description: "Um carro muito maneiro que faz muito barulho pras mina",
    year: 2012,
    km: 4542,
    price: 28.325,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/segmento-carros/01-images/onix-plus-premier.jpg?imwidth=419",
    model: "ONIX PLUS 10",
    mark: "Chevrolet",
    owner: "Ronaldinho das Mina",
  },
  {
    id: 11,
    description: "Muito bão viu, em ótimas condições, nunca deixou na mão.",
    year: 2022,
    km: 1242,
    price: 32.122,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/02-images/cruze-sport6-rs-carros.jpg?imwidth=419",
    model: "CRUZE SPORT6 RS 11",
    mark: "Chevrolet",
    owner: "Reginaldo Rossi",
  },
  {
    id: 12,
    description: "Um carro muito maneiro que faz muito barulho pras mina",
    year: 2012,
    km: 4542,
    price: 28.325,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/segmento-carros/01-images/onix-plus-premier.jpg?imwidth=419",
    model: "ONIX PLUS 12",
    mark: "Chevrolet",
    owner: "Ronaldinho das Mina",
  },
  {
    id: 13,
    description: "Um carro muito maneiro que faz muito barulho pras mina",
    year: 2012,
    km: 4542,
    price: 28.325,
    image:
      "https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/cars/cars-subcontent/segmento-carros/01-images/onix-plus-premier.jpg?imwidth=419",
    model: "ONIX PLUS 13",
    mark: "Chevrolet",
    owner: "Ronaldinho das Mina",
  },
];
